name: bell_security_app
description: A Security App for LGBT+ Community
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  awesome_dialog: ^2.1.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1
  equatable: ^2.0.3
  flutter_bloc: ^7.3.2
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.0
  plugin_platform_interface: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/google-logo.png
    - assets/bell-icon-logo.png
    - assets/bell-lgbt-logo.png
    - assets/rainbow-icon.png
    - assets/facebook.jpg
    - assets/google.jpg
    - assets/bracelet.jpg
    - assets/pendant.jpg
    - assets/ring.jpg
    - assets/yogi.jpg
    - assets/bracelet2.jpeg
    - assets/ring.jpeg
    - assets/bracelet.jpeg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
